### ISSUE TITLE
After uninstalling, I can't reinstall it again

### ISSUE THREAD

**Issue by yixuanjian** [lucwastiaux/mandarin-cantonese-api#1]
The add-on created a lot of errors since yesterday. So this morning I uninstalled it, but I can't reinstall it again. It keeps showing "Sign in with Google temporarily disabled for this app, This app has not been verified yet by Google in order to use Google Sign In." 

I need this app to work as a teacher, so could you please tell me how to solve this problem? Thank you!

**Comment by lucwastiaux** [comment]
please try to follow the manual install procedures described here: https://github.com/lucwastiaux/mandarin-cantonese-api#manually-enabling-the-add-on
