### ISSUE TITLE
#ERROR!  Service invoked too many times for one day

### ISSUE THREAD

**Issue by ryguy36** [lucwastiaux/mandarin-cantonese-api#2]
Exception: Service invoked too many times for one day: urlfetch. (line 67).
On some days, I get the attached error on all of the cells using this function. Refreshing the page doesn't help. Today it happened after opening my sheet just once.

Love this tool, by the way, makes my language learning so much easier. 

![image](https://user-images.githubusercontent.com/11969027/92832775-b0368700-f39d-11ea-884e-ff14dabfeb66.png)

**Comment by lucwastiaux** [comment]
Google places a limit on how many times an add-on makes queries to an external service. The workaround is to use Batch Mode, such that your entire column of chinese characters are converted in one go. It's described here: https://medium.com/@lucw/converting-chinese-characters-to-pinyin-jyutping-on-google-sheets-now-with-more-functionality-5047692950bf
let me know if you run into any issues.

**Comment by ryguy36** [comment]
Thanks for the quick response. I'm using about 10. I'm trying batch mode now and will need to wait for tomorrow. I'll let you know if there are more issues.

**Comment by lucwastiaux** [comment]
OK. If you find tomorrow that this solves the issue in a safisfactory way, please leave a positive review on the add-on.

**Comment by ryguy36** [comment]
That seems to be a good alternative. Closing case.
