### ISSUE TITLE
Service is unreachable on https, and 404s on http

### ISSUE THREAD

**Issue by expipiplus1** [lucwastiaux/mandarin-cantonese-api#3]
To reproduce:

- Copy the code published here into a google sheets
- Attempt to use the "pinyin" function
- Observe the error `Address unavailable: https://api.prod.mandarincantonese.com/batch`

- Switch to `http`
- Observe that one now gets a 404 error

One can also see this with:

`curl -XPOST -H "Content-type: application/json" -d "{'conversion': \"pinyin\", 'tone_numbers': false, 'spaces': false,'entries': [\"所\"]};" 'http://api.prod.mandarincantonese.com/batch'`

It does however still work using the published app, nasty that google doesn't let us see the source for that!

**Comment by lucwastiaux** [comment]
Yes please use the published add-on, the manual installation was only a temporary workaround until Google allowed installation of the add-on.

**Comment by expipiplus1** [comment]
Right, I'm actually trying to use it from a google app script so that's not possible.

I'm self hosting this now anyway which suits me. Thanks for this handy project!

**Comment by lucwastiaux** [comment]
OK, I take it you're satisfied to use the published addon with the PINYIN/JYUTPING functions ? If so then yes self hosting is the best approach.

**Comment by expipiplus1** [comment]
Yeah, that works for me, thanks.
