### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by expipiplus1** [lucwastiaux/mandarin-cantonese-api#4]
It would be handy to add a LICENSE file to this project.

**Comment by lucwastiaux** [comment]
OK, what sort of license would be suitable for this project?

**Comment by expipiplus1** [comment]
Up to you I guess, any of the popular ones here would be a good choice: https://opensource.org/licenses. I like BSD-3 because the mascot is a happy little daemon, Mozilla has a dinosaur mascot so that's also a good choice.

**Comment by expipiplus1** [comment]
Adding a license here would also allow me to easily package it for NixOS

**Comment by lucwastiaux** [comment]
you want to package this project or the underlying python module ?

**Comment by expipiplus1** [comment]
The project itself I suppose, whatever one gets from running start.sh :)

**Comment by lucwastiaux** [comment]
done, added GPL license for both projects.

**Comment by expipiplus1** [comment]
Thanks!
